:toc:
:toc-placement!:

= Qute 

toc::[]

Goals:

1. Simple syntax.
2. Async data resolution.
3. Great extensibility.
4. Powerful https://quarkus.io/[Quarkus] integration.

We believe that templates should contain minimal logic.
And this attitude affects the syntax and APIs heavily.

== Engine

You'll always need an engine instance first.
Let's start with the convenient `Engine.builder()`:

[source,java]
----
// Create a new engine and use the default value resolvers and section helpers
Engine engine = Engine.builder().addDefaultValueResolvers().addDefaultSectionHelpers().build();
----

`Engine` represents a central point for template management.
It has a dedicated configuration and a template cache.
Once we have an engine it's possible to parse a template and render our first "hello world":

[source,java]
----
Template myTemplate = engine.parse("Hello {this}!");
System.out.println(myTemplate.render("world")); // -> Hello world!
----

We can also register the template for later use:

[source,java]
----
engine.putTemplate("my", myTemplate);
System.out.println(engine.getTemplate("my").render("world")); // -> Hello world!
----

NOTE: `Engine.getTemplate()` is also used when including templates. See <<include_helper>>.

=== Template Locator

Manual registration is sometimes handy but it's also possible to register a template locator using `EngineBuilder.addLocator(Function<String, Optional<Reader>>)`.
This locator is used whenever the `Engine.getTemplate()` method is called and the engine has no template for a given id.

== Building Blocks

Dynamic parts of a template include:

* expressions: `{foo}`, `{item.get(name)}`, `{global:colors}`, `{name ?: 'John'}`
* sections: `{#if foo} Foo is true {/if}`
** the name in the closing tag is optional: `{#if foo} Foo is true {/}`
** a section can be empty: `{#userTag image=true /}`
* comments: `{! This is a comment}`, `{! foo.bar}`, `{! #if true}`

=== Expressions

An expression consists of an optional namespace followed by a colon `:` and parts separated by dot `.`.
The first part of the expression is always resolved against the <<current_context_object, current context object>>.
For an expression that starts with a namespace the current context object is found using the available `NamespaceResolver`s.
For an expression that does not start with a namespace the current context object is *derived from the position* of the tag.
All other parts are resolved using `ValueResolver`s against the result of the previous resolution.

For example, expression `{name}` has no namespace and single part - "name".
The "name" will be resolved using all available `ValueResolver` s against the current context object.
However, the expression `{global:colors}` has "global" namespace and single part - "colors".
First, all available `NamespaceResolver` s will be used to find the current context object.
And afterwards `ValueResolver` s will be used to resolve "colors" against the context object found. 

----
{name} <1>
{global:colors} <2> 
----
<1> no namespace, one part - name
<2> namespace global, one part - colors

An expression part could be a "virtual method" in which case the name can be followed by parameters in parentheses. 

----
{item.getLabels(1)} <1>
{name or 'John'} <2>
----
<1> no namespace, two parts - "item", "getLabels(1)", the second part is a virtual method with name "getLabels" and params "1"
<2> infix notation, translated to "name.or('John')", no namespace, two parts - "name", "or('John')"

[[current_context_object]]
==== Current Context

If an expression does not specify a namespace the current context object is derived from the position of the tag.
By default, the current context object is the root context object that is passed to the `Template.render()` method and is also always accessible using the `data` namespace.
However, section tags may change the current context object.
A typical example is each/for loop - during iteration the content of the section is rendered with each element as the current context object:

----
{name} <1>
{#each items}
 {name} <2>
 {data:name} <3>
{/each}
----
<1> this "name" is resolved against the root context object
<2> this "name" is resolved against the iteration element
<3> this "name" is resolved against the root context object

=== Sections

A section has a start tag - content starts with `#`, followed with the name of the secion such as `{#if}`, and an end tag - content starts with `/` and contains the optional name of the section `{/if}`.
The start tag can also define parameters.
A section contains one or more section *blocks*. 
The "main" block is always present.
Additional blocks start with a label and can also have parameters - `{:else if item.isActive}`.
A section helper that defines the logic of a section can "execute" any of the blocks and evaluate the parameters.

----
{#if item.name is 'sword'}
It's a sword!
{:else if item.name is 'shield'}
It's a shield!
{:else}
Item is nor a sword nor a shield.
{/if}
----

==== Built-in Sections

===== Loop Section

The loop section helper makes it possible to iterate over an instance of `Iterable`, `Map` entry set and `Stream`.
It has two flavors.
The first one is using `each` alias.

----
{#each items}
 {name} <1>
{/each}
----
<1> "name" is resolved against the current iteration element

The other one is using `for` alias and can specify the namespace used to reference the iteration element:
----
{#for item in items} <1>
  {item:name} <2>
{/for}
----
<1> "item" is the namespace
<2> The namespace is optional but makes it possible to distinguish the context object e.g. when using nested loops

It's also possible to access the iteration metadata inside the loop, under the `iter` namespace:
----
{#each items}
 {iter:count}. {name} <1>
{/each}
----
<1> `count` represents one-based index. Metadata also include zero-based `index`, `hasNext`, `odd`, `even`.

===== If Section

A basic control flow section.
The simplest possible version accepts a single parameter and renders the contet if it's evaluated to `true` (or `Boolean.TRUE`).

----
{#if item.active}
 This item is active.
{/if}
----

You can also use the following operators:

|===
|Operator |Aliases 

|equals 
|`eq`, `==`, `is` 

|not equals 
|`ne`, `!=`

|greater than 
|`gt`, `>`

|greater equals
|`ge`, `>=`

|less than 
|`lt`, `<`

|less equals 
|`le`, `<=`

|===

TODO: BigDecimal conversion etc.

----
{#if item.age > 10}
 This item is very old.
{/if}
----

You can add any number of "else" blocks:

----
{#if item.age > 10}
 This item is very old.
{:else if item.age > 5}
 This item is quite old.
{:else if item.age > 2}
 This item is old.
{:else}
 This item is not old at all!
{/if}
----

===== With Section

This section can be used to set the current context object.
This could be useful to simplify the template structure.

----
{#with item.parent}
 {name}  <1>
{/with}
----
<1> The name will be resolved against the `item.parent`.

It's also possible to specify an alias that can be used as a namespace:

----
{#with item.parent as myParent}
 {myParent:name}
{/with}
----

[[include_helper]]
===== Include/Insert Sections

These sections can be used to include another template and possibly override some parts of the template (template inheritance).

.Template "base"
[source,html]
----
<html>
<head>
<meta charset="UTF-8">
<title>{#insert title}Default Title{/insert}</title> <1>
</head>
<body>
    {#insert body}No body :-){/insert} <2>
</body>
</html>
----
<1> `insert` sections are used to specify parts that could be overriden by a template that includes the given template.
<2> An `insert` section may define the default content that is rendered if not overriden.

.Template "detail"
[source,html]
----
{#include base} <1>
    {:title}My Title{/title} <2>
    {:body}
    <div>
        My body.
    </div>
{/include}
----
<1> `include` section is used to specify the extended template.
<2> Blocks with labels are used to specify the parts that should be overriden.

NOTE: Section blocks can also define an optional end tag - `{/title}`.

[[user_tags]]
===== User-defined Tags

User-defined tags can be used to include a template and optionally pass some parameters.
Let's suppose we have a template called `item.html`:

[source,html]
----
{#if showImage} <1>
  {it.image} <2>
{/if}
----
<1> `showImage` is a named parameter.
<2> `it` is a special key that is replaced with the first unnamed param.

Now if we register this template under the `item` id and if we add a `UserTagSectionHelper` to the engine:

[source,java]
----
Engine engine = Engine.builder().addSectionHelper(new UserTagSectionHelper.Factory("item"))
                .build();
----

NOTE: In Quarkus, all files from the `META-INF/resources/tags` are registered and monitored automatically.

We can include the tag like this:

[source,html]
----
{#each items}
 {#item this showImage=true /} <1>
{/each}
----
<1> `this` is resolved to an iteration element and can be referenced using the `it` key in the tag template.

== Quarkus Integration

If you want to use Qute in your Quarkus application add the following dependency to your project:

[source,xml]
----
<dependency>
   <groupId>io.quarkus.qute</groupId>
   <artifactId>qute-quarkus</artifactId>
</dependency>
----

An `Engine` instance is automatically configured and a bean is also registered.
Moreover, it's possible to inject templates located in the `META-INF/resources/templates` directory: 

[source,java]
----
class MyBean {

  @Inject 
  Template items; <1>
  
  @ResourcePath("detail/items2_v1.html") <2>
  Template items2;
  
  @Inject
  Engine engine; <3>
  
}
----
<1> If there is no qualifier provided the field name is used to locate the template. In this particular case, the container will attempt to locate a template with path `META-INF/resources/templates/items.html`.
<2> This qualifier instructs the container to inject a template from a path relative from `META-INF/resources/templates`.
<3> Inject the configured `Engine` instance.

=== Injecting Beans In Templates

Any CDI bean annotated with `@Named` can be referenced in any template by using the `inject:` namespace.

[source,html]
----
{inject:myBean.price} <1>
----
<1> First, a bean with name `myBean` is found and then used as the base object.

NOTE: A `ValueResolver` is generated for all beans annotated with `@Named` so that it's possible to invoke any method without reflection.

=== Configuration

* `quarkus.qute.base-path` - a path relative from `META-INF/resources/`; all files in the base directory and its subdirectories are considered templates and watched for changes in the development mode
* `quarkus.qute.suffixes` - a set of suffixes used when attempting to locate a template; by default, `engine.getTemplate(foo)` would result in several lookups: `META-INF/resources/templates/foo`, `META-INF/resources/templates/foo.html` and `META-INF/resources/templates/foo.txt`

=== Template extension methods

A value resolver is automatically generated for template extension methods annotated with `@TemplateExtension`.
The method must be static, must not return `void` and must accept at least one parameter. 
The class of the first parameter is used to match the base object and the method name is used to match the property name.

[source,java]
----
class Item {

    public final BigDecimal price;

    public Item(BigDecimal price) {
        this.price = price;
    }
}

class MyExtension {

  @TemplateExtension
  static BigDecimal discountedPrice(Item item) {
     return item.getPrice().multiply(new BigDecimal("0.9"));
  }
}
----

This template extension method makes it possible to render the following template:

[source,html]
----
{#each items} <1>
   {discountedPrice}
{/each}
----
<1> Let's suppose that `items` is resolved to a list of `Item` instances.

=== Template data

A value resolver is automatically generated for a type annotated with `@TemplateData`.
Note that non-public members, constructors, static initializers, static, synthetic and void methods are always ignored.
This allows Quarkus to avoid using reflection to access the data in your classes.

[source,java]
----
@TemplateData
class Item {

    public final BigDecimal price;

    public Item(BigDecimal price) {
        this.price = price;
    }
}
----

Any instance of `Item` can be used directly in the template:

[source,html]
----
{#each items} <1>
   {price}
{/each}
----
<1> Let's suppose that `items` is resolved to a list of `Item` instances.

=== Variant Templates

Sometimes it could be useful to render a specific variant of the template based on the content negotiation.
`VariantTemplate` is a perfect match for this use case:

[source,java]
----
@Path("/detail")
class DetailResource {
  
  @Inject
  VariantTemplate item; <1>

  @GET
  @Produces({ MediaType.TEXT_HTML, MediaType.TEXT_PLAIN })
  public Rendering item() {
     return item.render().setData(new Item("Alpha", BigDecimal.valueOf(1000))); <2>
  }
}
----
<1> Inject a variant template with base path derived from the injected field - `META-INF/resources/templates/item`.
<2> The resulting output depends on the `Accept` header received from the client. For `text/plain` the `META-INF/resources/templates/item.txt` template is used. For `text/html` the `META-INF/resources/templates/item.html` template is used.

=== Development Mode

All files located in the `quarkus.qute.basePath` - `META-INF/resources/templates` by default - are watched for changes.
When a template is modified it is removed from the cache and the template source is parsed again.
In other words, there is no need to rebuild/restart the application when only modifying the templates.

== Extension Points

TODO

=== Section helpers

TODO
 
